export const generateHTML = (htmlDiv) => {
    return `<!DOCTYPE html>
    <html lang="en">
    
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="height=device-height,
                          width=device-width, initial-scale=1.0,
                          minimum-scale=1.0, maximum-scale=1.0,
                          user-scalable=no">
        <meta name="theme-color" content="#000000" />
        <meta name="description" content="HTML Generated by Versa" />
    
        <title>Versa</title>
    </head>
    
    <body>
    ${htmlDiv}
    </body>
    
    </html>`;
}